#!/bin/bash

########################## ****** ############################
make clean > /dev/null
make > /dev/null
########################## ****** ############################

########################## ****** ############################
### Arquivo de Entrada: ambiente.in (configurações)
read Nro_clientes
# echo $Nro_clientes
nro_clientes=`echo $Nro_clientes | cut -d " " -f 2`
#echo $nro_clientes

# Configurações
read Clients
#echo $Clients
read Hosts
#echo $Hosts

read jump
#echo $jump
read jump
#echo $jump

read dbDIR
#echo $dbDIR
########################## ****** ############################

########################## ****** ############################
# Gerando arquivo de dados de entrada para o servidor (DESCMon)
echo "NofClient=$nro_clientes" > servidor.in
echo $dbDIR >> servidor.in
########################## ****** ############################

########################## ****** ############################
# Lançando o servidor na máquina local (Ens5)
export loglevel=OFF
mvn exec:java -q -pl monitor -Dexec.mainClass="com.wsudesc.otavio.Monitor" < servidor.in > Logtrans.log&
########################## ****** ############################

########################## ****** ############################
# Lançando os clientes
for i in `seq 1 $nro_clientes`
do
    sleep 1
    pos=`expr $i + 1`;
    nom_maquinas=`echo $Hosts | cut -d " " -f $pos`
    # px=`echo $Clients | cut -d " " -f $pos`
    # cp db* FileDESC > /dev/null
    ssh $nom_maquinas "cd `pwd`; export loglevel=OFF; mvn exec:java -q -pl client -Dexec.mainClass="com.wsudesc.otavio.Client" ;  cd - > /dev/null"
done
########################## ****** ############################

tar xvzf auditor.tgz > /dev/null 2>&1
cd _auditor_ > /dev/null 2>&1
make > /dev/null 2>&1
cp -r ../input ../output ../tempfiles .
mkdir auditor/tmp

cd auditor ; java -cp  target/auditor-1.0-SNAPSHOT.jar:com/dropbox/core/dropbox-core-sdk/4.0.1/dropbox-core-sdk-4.0.1.jar:com/fasterxml/jackson/core/jackson-core/2.7.4/jackson-core-2.7.4.jar com.wsudesc.app.Auditor `pwd` < ../../Logtrans.log; cd - > /dev/null 2>&1
